import { test } from "node:test";
import assert from "node:assert/strict";
import { interpretScene, modelConfiguration, sceneValidationIssue, scenePrompt } from "./engine.mjs";
import { SCENE_RESPONSE_SCHEMA } from "./sceneResponseSchema.mjs";

const scene = { entities: [], relations: [] };
const makePlan = () => ({ blueprintVersion: "1.0", mode: "replace", confidence: 0.9,
  objects: ["oscillator", "membrane", "vibration", "sensor"].map((label, index) => ({ id: `r${index}`, label, kind: "generic", x: 10 + index * 25, y: 50 })),
  connections: [{ from: "r0", to: "r2", kind: "emits", label: "emits" },
    { from: "r2", to: "r1", kind: "propagatesThrough", label: "propagates through" },
    { from: "r2", to: "r3", kind: "reaches", label: "reaches" }] });

test("service protocol advertises and validates propagation roles", () => {
  assert.equal(sceneValidationIssue(makePlan(), scene), null);
  assert.match(scenePrompt("explain", scene), /payload→medium propagatesThrough/);
  assert.ok(JSON.stringify(SCENE_RESPONSE_SCHEMA).includes('"propagatesThrough"'));
});
test("partial, reversed and mixed propagation graphs fail closed", () => {
  for (let index = 0; index < 3; index++) {
    const plan = makePlan(); plan.connections.splice(index, 1);
    assert.match(sceneValidationIssue(plan, scene), /Propagation needs/);
  }
  const swapped = makePlan(); swapped.connections[1].to = "r0";
  assert.match(sceneValidationIssue(swapped, scene), /Propagation needs/);
  const extra = makePlan(); extra.connections.push({ from: "r0", to: "r3", label: "causes", kind: "causes" });
  assert.match(sceneValidationIssue(extra, scene), /Propagation needs/);
});

test("repair feedback identifies an incorrect final arrow without changing it automatically", () => {
  const plan = makePlan(); plan.connections[2].from = "r1";
  assert.match(sceneValidationIssue(plan, scene), /travelling payload r2, not r1/);
  assert.equal(plan.connections[2].from, "r1");
});

test("a passive emitter modifier does not send the emitter through the medium", () => {
  const plan = makePlan();
  const text = "Vibration generated by an oscillator propagates through a membrane to a sensor.";
  assert.equal(sceneValidationIssue(plan, scene, text), null);
  plan.connections[1].from = "r0";
  assert.ok(sceneValidationIssue(plan, scene, text));
});
test("mocked provider returns a complete propagation plan in one attempt", async () => {
  let calls = 0;
  const result = await interpretScene({ text: "Vibration crosses the membrane between the oscillator and sensor.", scene },
    modelConfiguration({ NEBIUS_API_KEY: "test-only" }), { fetchImpl: async () => {
      calls++;
      return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify(makePlan()) } }] }), { status: 200 });
    } });
  assert.equal(calls, 1);
  assert.equal(result.candidate.connections[1].kind, "propagatesThrough");
});
